version: "3.8"
services:
  backend:
    build: ./backend
    container_name: todo-backend
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/tododb
  frontend:
    build: ./frontend
    container_name: todo-frontend
    ports:
      - "3000:3000"
  db:
    image: postgres
    container_name: todo-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tododb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
